from pathlib import Path
root = Path('/mnt/data/barbearia-app')
files = {}
files['package.json'] = r'''{
  "name": "barbearia-app",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "prisma generate && next build",
    "start": "next start",
    "lint": "next lint",
    "prisma:generate": "prisma generate",
    "prisma:migrate": "prisma migrate dev",
    "prisma:deploy": "prisma migrate deploy",
    "seed": "node prisma/seed.js"
  },
  "dependencies": {
    "@mercadopago/sdk-react": "^0.0.23",
    "@prisma/client": "^5.22.0",
    "bcryptjs": "^2.4.3",
    "mercadopago": "^2.6.0",
    "next": "14.2.30",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "zod": "^3.24.1"
  },
  "devDependencies": {
    "prisma": "^5.22.0",
    "typescript": "^5.6.3",
    "@types/node": "^22.10.2",
    "@types/react": "^18.3.18",
    "@types/react-dom": "^18.3.5"
  }
}
'''
files['tsconfig.json'] = r'''{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
'''
files['next-env.d.ts'] = '/// <reference types="next" />\n/// <reference types="next/image-types/global" />\n\n// This file is auto-generated by Next.js\n'
files['next.config.mjs'] = r'''/** @type {import('next').NextConfig} */
const nextConfig = {
  experimental: {
    serverActions: {
      bodySizeLimit: '2mb'
    }
  }
};

export default nextConfig;
'''
files['.env.example'] = r'''# Banco local para desenvolvimento
DATABASE_URL="file:./dev.db"

# Login do barbeiro/admin
ADMIN_EMAIL="admin@barbearia.com"
ADMIN_PASSWORD="123456"
AUTH_SECRET="troque-essa-chave-por-uma-bem-grande"

# URL pública do site em produção
NEXT_PUBLIC_APP_URL="http://localhost:3000"

# WhatsApp do barbeiro em formato internacional, sem + nem espaços
# Exemplo Brasil SP: 5511999999999
BARBER_WHATSAPP_NUMBER="5511999999999"

# Mercado Pago
MERCADO_PAGO_ACCESS_TOKEN="TEST-xxxxxxxxxxxxxxxx"
MERCADO_PAGO_WEBHOOK_SECRET="troque-se-quiser-validar-webhook"
'''
files['middleware.ts'] = r'''import { NextRequest, NextResponse } from "next/server";

export function middleware(request: NextRequest) {
  if (!request.nextUrl.pathname.startsWith("/admin") || request.nextUrl.pathname.startsWith("/admin/login")) {
    return NextResponse.next();
  }

  const token = request.cookies.get("barber_admin_session")?.value;
  if (!token) {
    return NextResponse.redirect(new URL("/admin/login", request.url));
  }

  return NextResponse.next();
}

export const config = {
  matcher: ["/admin/:path*"]
};
'''
files['prisma/schema.prisma'] = r'''generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model Appointment {
  id          String   @id @default(cuid())
  customer    String
  phone       String
  email       String?
  service     String
  barber      String
  date        String
  time        String
  notes       String?
  status      String   @default("confirmado")
  whatsappUrl String
  createdAt   DateTime @default(now())
}

model Product {
  id          String      @id @default(cuid())
  name        String
  description String
  price       Float
  imageUrl    String?
  stock       Int         @default(0)
  active      Boolean     @default(true)
  createdAt   DateTime    @default(now())
  updatedAt   DateTime    @updatedAt
  orderItems  OrderItem[]
}

model Order {
  id                  String      @id @default(cuid())
  customerName        String
  customerEmail       String
  customerPhone       String
  total               Float
  status              String      @default("pending")
  mercadoPagoId       String?
  mercadoPagoStatus   String?
  mercadoPagoPrefId   String?
  createdAt           DateTime    @default(now())
  updatedAt           DateTime    @updatedAt
  items               OrderItem[]
}

model OrderItem {
  id        String   @id @default(cuid())
  orderId   String
  productId String
  quantity  Int
  price     Float
  order     Order    @relation(fields: [orderId], references: [id], onDelete: Cascade)
  product   Product  @relation(fields: [productId], references: [id])
}
'''
files['prisma/seed.js'] = r'''const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const products = [
    {
      name: 'Pomada Modeladora',
      description: 'Fixação média com acabamento natural.',
      price: 39.9,
      stock: 15,
      imageUrl: 'https://images.unsplash.com/photo-1621607512022-6aecc4fed814?auto=format&fit=crop&w=800&q=80'
    },
    {
      name: 'Óleo para Barba',
      description: 'Hidratação e maciez para barba e pele.',
      price: 29.9,
      stock: 20,
      imageUrl: 'https://images.unsplash.com/photo-1517837016564-bfc28f6b3b0a?auto=format&fit=crop&w=800&q=80'
    },
    {
      name: 'Shampoo Masculino',
      description: 'Limpeza refrescante para uso diário.',
      price: 24.9,
      stock: 18,
      imageUrl: 'https://images.unsplash.com/photo-1526947425960-945c6e72858f?auto=format&fit=crop&w=800&q=80'
    }
  ];

  for (const product of products) {
    await prisma.product.upsert({
      where: { id: product.name.toLowerCase().replace(/\s+/g, '-') },
      update: product,
      create: { id: product.name.toLowerCase().replace(/\s+/g, '-'), ...product }
    }).catch(async () => {
      const found = await prisma.product.findFirst({ where: { name: product.name } });
      if (!found) await prisma.product.create({ data: product });
    });
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
'''
files['lib/prisma.ts'] = r'''import { PrismaClient } from "@prisma/client";

declare global {
  var prisma: PrismaClient | undefined;
}

export const prisma = global.prisma || new PrismaClient();
if (process.env.NODE_ENV !== "production") global.prisma = prisma;
'''
files['lib/auth.ts'] = r'''import crypto from "crypto";

const COOKIE_NAME = "barber_admin_session";

function sign(value: string) {
  const secret = process.env.AUTH_SECRET || "dev-secret";
  return crypto.createHmac("sha256", secret).update(value).digest("hex");
}

export function createSessionValue(email: string) {
  const payload = `${email}.${Date.now()}`;
  return `${payload}.${sign(payload)}`;
}

export function verifySessionValue(value: string) {
  const parts = value.split(".");
  if (parts.length < 3) return false;
  const signature = parts.pop() as string;
  const payload = parts.join(".");
  return sign(payload) === signature;
}

export const SESSION_COOKIE_NAME = COOKIE_NAME;
'''
files['lib/mercadopago.ts'] = r'''import { MercadoPagoConfig, Preference } from "mercadopago";

export function getMercadoPagoClient() {
  const accessToken = process.env.MERCADO_PAGO_ACCESS_TOKEN;
  if (!accessToken) {
    throw new Error("MERCADO_PAGO_ACCESS_TOKEN não configurado.");
  }

  return new MercadoPagoConfig({ accessToken });
}

export function getPreferenceClient() {
  return new Preference(getMercadoPagoClient());
}
'''
files['lib/utils.ts'] = r'''export function formatCurrency(value: number) {
  return new Intl.NumberFormat("pt-BR", {
    style: "currency",
    currency: "BRL"
  }).format(value);
}

export function buildWhatsAppUrl(message: string) {
  const number = process.env.BARBER_WHATSAPP_NUMBER || "";
  return `https://wa.me/${number}?text=${encodeURIComponent(message)}`;
}
'''
files['components/Header.tsx'] = r'''import Link from "next/link";

export function Header() {
  return (
    <header className="border-b border-zinc-800 bg-zinc-950/95 sticky top-0 z-50">
      <div className="mx-auto flex max-w-6xl items-center justify-between px-4 py-4">
        <Link href="/" className="text-xl font-bold tracking-wide text-white">
          BarberPro
        </Link>
        <nav className="flex gap-4 text-sm text-zinc-300">
          <Link href="/agendar">Agendar</Link>
          <Link href="/produtos">Produtos</Link>
          <Link href="/admin">Painel</Link>
        </nav>
      </div>
    </header>
  );
}
'''
files['components/Footer.tsx'] = r'''export function Footer() {
  return (
    <footer className="border-t border-zinc-800 bg-zinc-950">
      <div className="mx-auto max-w-6xl px-4 py-8 text-sm text-zinc-400">
        Projeto de barbearia com agendamento, WhatsApp e Mercado Pago.
      </div>
    </footer>
  );
}
'''
files['components/AppointmentForm.tsx'] = r'''"use client";

import { useState } from "react";

const services = [
  "Corte",
  "Barba",
  "Sobrancelha",
  "Corte + Barba",
  "Pigmentação",
  "Hidratação"
];

const barbers = ["Wadisson", "Lucas", "Mateus"];
const times = [
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30"
];

export function AppointmentForm() {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ message: string; whatsappUrl?: string } | null>(null);

  async function onSubmit(formData: FormData) {
    setLoading(true);
    setResult(null);

    const payload = Object.fromEntries(formData.entries());
    const response = await fetch("/api/appointments", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload)
    });

    const data = await response.json();
    setResult(data);
    setLoading(false);
  }

  return (
    <div className="grid gap-6 md:grid-cols-[1.2fr_0.8fr]">
      <form action={onSubmit} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6 shadow-lg">
        <div className="grid gap-4 md:grid-cols-2">
          <input name="customer" placeholder="Seu nome" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required />
          <input name="phone" placeholder="WhatsApp" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required />
          <input name="email" type="email" placeholder="E-mail (opcional)" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" />
          <select name="service" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required>
            <option value="">Escolha o serviço</option>
            {services.map((service) => (
              <option key={service} value={service}>{service}</option>
            ))}
          </select>
          <select name="barber" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required>
            <option value="">Escolha o barbeiro</option>
            {barbers.map((barber) => (
              <option key={barber} value={barber}>{barber}</option>
            ))}
          </select>
          <input name="date" type="date" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required />
          <select name="time" className="rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required>
            <option value="">Horário</option>
            {times.map((time) => (
              <option key={time} value={time}>{time}</option>
            ))}
          </select>
        </div>
        <textarea name="notes" placeholder="Observações" className="mt-4 min-h-28 w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" />
        <button disabled={loading} className="mt-4 rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-black transition hover:opacity-90 disabled:opacity-60">
          {loading ? "Agendando..." : "Confirmar agendamento"}
        </button>
      </form>

      <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
        <h3 className="text-xl font-semibold text-white">Como funciona</h3>
        <ol className="mt-4 space-y-3 text-zinc-300">
          <li>1. O cliente escolhe serviço, barbeiro, data e horário.</li>
          <li>2. O sistema salva o agendamento no banco.</li>
          <li>3. É criada uma mensagem pronta para o WhatsApp do barbeiro.</li>
          <li>4. O barbeiro visualiza o horário no painel.</li>
        </ol>

        {result && (
          <div className="mt-6 rounded-xl border border-zinc-700 bg-zinc-950 p-4">
            <p className="text-sm text-zinc-200">{result.message}</p>
            {result.whatsappUrl && (
              <a href={result.whatsappUrl} target="_blank" className="mt-3 inline-block rounded-lg bg-emerald-500 px-4 py-2 text-sm font-semibold text-black">
                Abrir WhatsApp do barbeiro
              </a>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
'''
files['components/ProductGrid.tsx'] = r'''"use client";

import { useMemo, useState } from "react";
import { formatCurrency } from "@/lib/utils";

type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  imageUrl: string | null;
  stock: number;
};

export function ProductGrid({ products }: { products: Product[] }) {
  const [cart, setCart] = useState<Record<string, number>>({});
  const [customerName, setCustomerName] = useState("");
  const [customerEmail, setCustomerEmail] = useState("");
  const [customerPhone, setCustomerPhone] = useState("");
  const [loading, setLoading] = useState(false);

  const total = useMemo(() => {
    return products.reduce((acc, product) => acc + product.price * (cart[product.id] || 0), 0);
  }, [cart, products]);

  function add(id: string) {
    setCart((prev) => ({ ...prev, [id]: (prev[id] || 0) + 1 }));
  }

  function remove(id: string) {
    setCart((prev) => ({ ...prev, [id]: Math.max(0, (prev[id] || 0) - 1) }));
  }

  async function checkout() {
    const items = Object.entries(cart)
      .filter(([, quantity]) => quantity > 0)
      .map(([productId, quantity]) => ({ productId, quantity }));

    if (!items.length) {
      alert("Adicione pelo menos um produto.");
      return;
    }

    if (!customerName || !customerEmail || !customerPhone) {
      alert("Preencha seus dados para finalizar.");
      return;
    }

    setLoading(true);

    const response = await fetch("/api/checkout", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ customerName, customerEmail, customerPhone, items })
    });

    const data = await response.json();
    setLoading(false);

    if (!response.ok) {
      alert(data.message || "Erro ao iniciar pagamento.");
      return;
    }

    window.location.href = data.initPoint;
  }

  return (
    <div className="grid gap-6 lg:grid-cols-[1fr_360px]">
      <div className="grid gap-6 md:grid-cols-2 xl:grid-cols-3">
        {products.map((product) => (
          <div key={product.id} className="overflow-hidden rounded-2xl border border-zinc-800 bg-zinc-900">
            {product.imageUrl ? (
              <img src={product.imageUrl} alt={product.name} className="h-52 w-full object-cover" />
            ) : (
              <div className="flex h-52 items-center justify-center bg-zinc-800 text-zinc-400">Sem imagem</div>
            )}
            <div className="p-5">
              <h3 className="text-lg font-semibold text-white">{product.name}</h3>
              <p className="mt-2 text-sm text-zinc-400">{product.description}</p>
              <p className="mt-3 text-emerald-400 font-semibold">{formatCurrency(product.price)}</p>
              <p className="mt-1 text-xs text-zinc-500">Estoque: {product.stock}</p>
              <div className="mt-4 flex items-center gap-3">
                <button onClick={() => remove(product.id)} className="rounded-lg border border-zinc-700 px-3 py-1 text-white">-</button>
                <span className="min-w-8 text-center text-white">{cart[product.id] || 0}</span>
                <button onClick={() => add(product.id)} className="rounded-lg bg-emerald-500 px-3 py-1 font-semibold text-black">+</button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <aside className="h-fit rounded-2xl border border-zinc-800 bg-zinc-900 p-5 lg:sticky lg:top-24">
        <h3 className="text-xl font-semibold text-white">Finalizar compra</h3>
        <div className="mt-4 space-y-3">
          <input value={customerName} onChange={(e) => setCustomerName(e.target.value)} placeholder="Seu nome" className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" />
          <input value={customerEmail} onChange={(e) => setCustomerEmail(e.target.value)} type="email" placeholder="Seu e-mail" className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" />
          <input value={customerPhone} onChange={(e) => setCustomerPhone(e.target.value)} placeholder="Seu WhatsApp" className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" />
        </div>
        <div className="mt-4 space-y-2 text-sm text-zinc-300">
          {products.filter((product) => (cart[product.id] || 0) > 0).map((product) => (
            <div key={product.id} className="flex items-center justify-between">
              <span>{product.name} x {cart[product.id]}</span>
              <span>{formatCurrency(product.price * (cart[product.id] || 0))}</span>
            </div>
          ))}
        </div>
        <div className="mt-4 flex items-center justify-between border-t border-zinc-800 pt-4 text-white">
          <span>Total</span>
          <strong>{formatCurrency(total)}</strong>
        </div>
        <button onClick={checkout} disabled={loading} className="mt-4 w-full rounded-xl bg-sky-500 px-4 py-3 font-semibold text-black disabled:opacity-60">
          {loading ? "Redirecionando..." : "Pagar com Mercado Pago"}
        </button>
      </aside>
    </div>
  );
}
'''
files['components/AdminLogoutButton.tsx'] = r'''"use client";

export function AdminLogoutButton() {
  async function logout() {
    await fetch("/api/admin/logout", { method: "POST" });
    window.location.href = "/admin/login";
  }

  return (
    <button onClick={logout} className="rounded-xl border border-zinc-700 px-4 py-2 text-sm text-white">
      Sair
    </button>
  );
}
'''
files['app/globals.css'] = r'''@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  color-scheme: dark;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  background: #09090b;
  color: #fafafa;
}

a {
  color: inherit;
  text-decoration: none;
}
'''
files['tailwind.config.ts'] = r'''import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}"
  ],
  theme: { extend: {} },
  plugins: []
};

export default config;
'''
files['postcss.config.js'] = r'''module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {}
  }
};
'''
# Need dependencies tailwind/postcss/autoprefixer
files['package.json'] = files['package.json'].replace('"typescript": "^5.6.3",\n    "@types/node": "^22.10.2",', '"typescript": "^5.6.3",\n    "tailwindcss": "^3.4.17",\n    "postcss": "^8.4.49",\n    "autoprefixer": "^10.4.20",\n    "@types/node": "^22.10.2",')
files['app/layout.tsx'] = r'''import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "BarberPro",
  description: "Barbearia com agendamento, WhatsApp e Mercado Pago"
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="pt-BR">
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
'''
files['app/page.tsx'] = r'''import Link from "next/link";

const services = [
  { name: "Corte", price: "R$ 35" },
  { name: "Barba", price: "R$ 25" },
  { name: "Sobrancelha", price: "R$ 15" },
  { name: "Corte + Barba", price: "R$ 55" }
];

export default function HomePage() {
  return (
    <div>
      <section className="mx-auto grid max-w-6xl gap-10 px-4 py-16 md:grid-cols-2 md:items-center">
        <div>
          <span className="rounded-full border border-emerald-500/40 bg-emerald-500/10 px-3 py-1 text-sm text-emerald-400">
            Sistema completo para barbearia
          </span>
          <h1 className="mt-5 text-4xl font-bold tracking-tight text-white md:text-6xl">
            Agendamento online, WhatsApp e vendas no mesmo site.
          </h1>
          <p className="mt-5 max-w-xl text-lg text-zinc-300">
            O cliente agenda o horário, o barbeiro recebe a mensagem no WhatsApp e ainda vende produtos com pagamento via Mercado Pago.
          </p>
          <div className="mt-8 flex flex-wrap gap-4">
            <Link href="/agendar" className="rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-black">Agendar agora</Link>
            <Link href="/produtos" className="rounded-xl border border-zinc-700 px-5 py-3 font-semibold text-white">Ver produtos</Link>
          </div>
        </div>
        <div className="rounded-3xl border border-zinc-800 bg-gradient-to-br from-zinc-900 to-zinc-950 p-8 shadow-2xl">
          <div className="grid gap-4 sm:grid-cols-2">
            <div className="rounded-2xl bg-zinc-900 p-5">
              <p className="text-sm text-zinc-400">Agendamentos hoje</p>
              <p className="mt-2 text-3xl font-bold text-white">12</p>
            </div>
            <div className="rounded-2xl bg-zinc-900 p-5">
              <p className="text-sm text-zinc-400">Produtos vendidos</p>
              <p className="mt-2 text-3xl font-bold text-white">27</p>
            </div>
            <div className="rounded-2xl bg-zinc-900 p-5 sm:col-span-2">
              <p className="text-sm text-zinc-400">Fluxo do projeto</p>
              <p className="mt-2 text-zinc-200">Cliente agenda → sistema salva → WhatsApp do barbeiro → barbeiro vê no painel → cliente compra produtos.</p>
            </div>
          </div>
        </div>
      </section>

      <section className="mx-auto max-w-6xl px-4 py-8">
        <h2 className="text-3xl font-bold text-white">Serviços</h2>
        <div className="mt-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          {services.map((service) => (
            <div key={service.name} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">
              <h3 className="text-lg font-semibold text-white">{service.name}</h3>
              <p className="mt-2 text-zinc-400">Preço inicial</p>
              <p className="mt-1 font-bold text-emerald-400">{service.price}</p>
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
'''
files['app/agendar/page.tsx'] = r'''import { AppointmentForm } from "@/components/AppointmentForm";

export default function AgendarPage() {
  return (
    <section className="mx-auto max-w-6xl px-4 py-16">
      <h1 className="text-4xl font-bold text-white">Agendar horário</h1>
      <p className="mt-3 max-w-2xl text-zinc-300">
        Escolha o serviço, o barbeiro e o horário. O sistema cadastra o agendamento e gera a mensagem para WhatsApp.
      </p>
      <div className="mt-8">
        <AppointmentForm />
      </div>
    </section>
  );
}
'''
files['app/produtos/page.tsx'] = r'''import { ProductGrid } from "@/components/ProductGrid";
import { prisma } from "@/lib/prisma";

export default async function ProdutosPage() {
  const products = await prisma.product.findMany({ where: { active: true }, orderBy: { createdAt: "desc" } });

  return (
    <section className="mx-auto max-w-6xl px-4 py-16">
      <h1 className="text-4xl font-bold text-white">Produtos</h1>
      <p className="mt-3 text-zinc-300">Venda produtos da barbearia com checkout do Mercado Pago.</p>
      <div className="mt-8">
        <ProductGrid products={products} />
      </div>
    </section>
  );
}
'''
files['app/admin/login/page.tsx'] = r'''export default function AdminLoginPage() {
  return (
    <section className="mx-auto flex min-h-[70vh] max-w-md items-center px-4 py-16">
      <form method="POST" action="/api/admin/login" className="w-full rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
        <h1 className="text-3xl font-bold text-white">Login do barbeiro</h1>
        <p className="mt-2 text-zinc-400">Use o e-mail e a senha definidos no arquivo .env</p>
        <div className="mt-6 space-y-4">
          <input name="email" type="email" placeholder="E-mail" className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required />
          <input name="password" type="password" placeholder="Senha" className="w-full rounded-xl bg-zinc-950 px-4 py-3 text-white outline-none" required />
        </div>
        <button className="mt-5 w-full rounded-xl bg-emerald-500 px-5 py-3 font-semibold text-black">Entrar</button>
      </form>
    </section>
  );
}
'''
files['app/admin/page.tsx'] = r'''import { prisma } from "@/lib/prisma";
import { formatCurrency } from "@/lib/utils";
import { AdminLogoutButton } from "@/components/AdminLogoutButton";

export default async function AdminPage() {
  const [appointments, products, orders] = await Promise.all([
    prisma.appointment.findMany({ orderBy: { createdAt: "desc" }, take: 20 }),
    prisma.product.findMany({ orderBy: { createdAt: "desc" } }),
    prisma.order.findMany({ orderBy: { createdAt: "desc" }, take: 20, include: { items: { include: { product: true } } } })
  ]);

  const todayAppointments = appointments.filter((a) => a.date === new Date().toISOString().slice(0, 10)).length;
  const paidRevenue = orders.filter((o) => o.status === "paid").reduce((acc, order) => acc + order.total, 0);

  return (
    <section className="mx-auto max-w-6xl px-4 py-10">
      <div className="flex flex-wrap items-center justify-between gap-4">
        <div>
          <h1 className="text-4xl font-bold text-white">Painel do barbeiro</h1>
          <p className="mt-2 text-zinc-400">Visualize agenda, vendas e produtos.</p>
        </div>
        <AdminLogoutButton />
      </div>

      <div className="mt-8 grid gap-4 md:grid-cols-3">
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">
          <p className="text-sm text-zinc-400">Agendamentos hoje</p>
          <p className="mt-2 text-3xl font-bold text-white">{todayAppointments}</p>
        </div>
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">
          <p className="text-sm text-zinc-400">Produtos cadastrados</p>
          <p className="mt-2 text-3xl font-bold text-white">{products.length}</p>
        </div>
        <div className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">
          <p className="text-sm text-zinc-400">Receita paga</p>
          <p className="mt-2 text-3xl font-bold text-emerald-400">{formatCurrency(paidRevenue)}</p>
        </div>
      </div>

      <div className="mt-8 grid gap-8 lg:grid-cols-[1.1fr_0.9fr]">
        <div>
          <h2 className="mb-4 text-2xl font-semibold text-white">Últimos agendamentos</h2>
          <div className="overflow-hidden rounded-2xl border border-zinc-800">
            <table className="min-w-full bg-zinc-900 text-sm">
              <thead className="bg-zinc-950 text-zinc-400">
                <tr>
                  <th className="px-4 py-3 text-left">Cliente</th>
                  <th className="px-4 py-3 text-left">Serviço</th>
                  <th className="px-4 py-3 text-left">Barbeiro</th>
                  <th className="px-4 py-3 text-left">Data</th>
                  <th className="px-4 py-3 text-left">Hora</th>
                </tr>
              </thead>
              <tbody>
                {appointments.map((appointment) => (
                  <tr key={appointment.id} className="border-t border-zinc-800 text-zinc-200">
                    <td className="px-4 py-3">{appointment.customer}</td>
                    <td className="px-4 py-3">{appointment.service}</td>
                    <td className="px-4 py-3">{appointment.barber}</td>
                    <td className="px-4 py-3">{appointment.date}</td>
                    <td className="px-4 py-3">{appointment.time}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        <div>
          <h2 className="mb-4 text-2xl font-semibold text-white">Pedidos</h2>
          <div className="space-y-4">
            {orders.map((order) => (
              <div key={order.id} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-5">
                <div className="flex items-start justify-between gap-4">
                  <div>
                    <p className="font-semibold text-white">{order.customerName}</p>
                    <p className="text-sm text-zinc-400">{order.customerEmail}</p>
                  </div>
                  <span className="rounded-full border border-zinc-700 px-3 py-1 text-xs uppercase text-zinc-300">{order.status}</span>
                </div>
                <div className="mt-3 space-y-1 text-sm text-zinc-300">
                  {order.items.map((item) => (
                    <p key={item.id}>{item.product.name} x {item.quantity}</p>
                  ))}
                </div>
                <p className="mt-3 font-semibold text-emerald-400">{formatCurrency(order.total)}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}
'''
files['app/sucesso/page.tsx'] = r'''export default function SucessoPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 text-center">
      <h1 className="text-4xl font-bold text-white">Pagamento iniciado</h1>
      <p className="mt-4 text-zinc-300">
        Quando o Mercado Pago confirmar o pagamento, o pedido será atualizado automaticamente pelo webhook.
      </p>
    </section>
  );
}
'''
files['app/falha/page.tsx'] = r'''export default function FalhaPage() {
  return (
    <section className="mx-auto max-w-3xl px-4 py-16 text-center">
      <h1 className="text-4xl font-bold text-white">Pagamento não concluído</h1>
      <p className="mt-4 text-zinc-300">O cliente pode voltar para a loja e tentar novamente.</p>
    </section>
  );
}
'''
files['app/api/appointments/route.ts'] = r'''import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { buildWhatsAppUrl } from "@/lib/utils";

const appointmentSchema = z.object({
  customer: z.string().min(2),
  phone: z.string().min(8),
  email: z.string().email().optional().or(z.literal("")),
  service: z.string().min(2),
  barber: z.string().min(2),
  date: z.string().min(10),
  time: z.string().min(4),
  notes: z.string().optional()
});

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const parsed = appointmentSchema.parse(body);

    const existing = await prisma.appointment.findFirst({
      where: {
        barber: parsed.barber,
        date: parsed.date,
        time: parsed.time,
        status: { not: "cancelado" }
      }
    });

    if (existing) {
      return NextResponse.json({ message: "Esse horário já está ocupado para esse barbeiro." }, { status: 400 });
    }

    const message = `Novo agendamento%0ACliente: ${parsed.customer}%0AServiço: ${parsed.service}%0ABarbeiro: ${parsed.barber}%0AData: ${parsed.date}%0AHorário: ${parsed.time}%0ATelefone: ${parsed.phone}${parsed.notes ? `%0AObs: ${parsed.notes}` : ""}`;
    const whatsappUrl = buildWhatsAppUrl(message);

    await prisma.appointment.create({
      data: {
        customer: parsed.customer,
        phone: parsed.phone,
        email: parsed.email || null,
        service: parsed.service,
        barber: parsed.barber,
        date: parsed.date,
        time: parsed.time,
        notes: parsed.notes,
        whatsappUrl
      }
    });

    return NextResponse.json({
      message: "Agendamento confirmado com sucesso.",
      whatsappUrl
    });
  } catch (error) {
    return NextResponse.json({ message: "Não foi possível concluir o agendamento.", error: String(error) }, { status: 500 });
  }
}
'''
files['app/api/checkout/route.ts'] = r'''import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { getPreferenceClient } from "@/lib/mercadopago";

const schema = z.object({
  customerName: z.string().min(2),
  customerEmail: z.string().email(),
  customerPhone: z.string().min(8),
  items: z.array(z.object({ productId: z.string(), quantity: z.number().int().positive() })).min(1)
});

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const parsed = schema.parse(body);

    const dbProducts = await prisma.product.findMany({
      where: { id: { in: parsed.items.map((item) => item.productId) } }
    });

    const missing = parsed.items.find((item) => !dbProducts.find((product) => product.id === item.productId));
    if (missing) {
      return NextResponse.json({ message: "Produto inválido no carrinho." }, { status: 400 });
    }

    const orderTotal = parsed.items.reduce((acc, item) => {
      const product = dbProducts.find((p) => p.id === item.productId)!;
      return acc + product.price * item.quantity;
    }, 0);

    const order = await prisma.order.create({
      data: {
        customerName: parsed.customerName,
        customerEmail: parsed.customerEmail,
        customerPhone: parsed.customerPhone,
        total: orderTotal,
        items: {
          create: parsed.items.map((item) => {
            const product = dbProducts.find((p) => p.id === item.productId)!;
            return {
              productId: item.productId,
              quantity: item.quantity,
              price: product.price
            };
          })
        }
      }
    });

    const baseUrl = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";
    const preferenceClient = getPreferenceClient();
    const preference = await preferenceClient.create({
      body: {
        items: parsed.items.map((item) => {
          const product = dbProducts.find((p) => p.id === item.productId)!;
          return {
            id: product.id,
            title: product.name,
            quantity: item.quantity,
            unit_price: product.price,
            currency_id: "BRL"
          };
        }),
        payer: {
          name: parsed.customerName,
          email: parsed.customerEmail
        },
        external_reference: order.id,
        notification_url: `${baseUrl}/api/mercadopago/webhook`,
        back_urls: {
          success: `${baseUrl}/sucesso`,
          failure: `${baseUrl}/falha`,
          pending: `${baseUrl}/sucesso`
        },
        auto_return: "approved"
      }
    });

    await prisma.order.update({
      where: { id: order.id },
      data: { mercadoPagoPrefId: preference.id }
    });

    return NextResponse.json({
      initPoint: preference.init_point,
      preferenceId: preference.id
    });
  } catch (error) {
    return NextResponse.json({ message: "Erro ao criar checkout.", error: String(error) }, { status: 500 });
  }
}
'''
files['app/api/mercadopago/webhook/route.ts'] = r'''import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { getMercadoPagoClient } from "@/lib/mercadopago";
import { Payment } from "mercadopago";

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => null);
    const topic = new URL(request.url).searchParams.get("topic") || body?.type;
    const paymentId = new URL(request.url).searchParams.get("id") || body?.data?.id;

    if (topic !== "payment" || !paymentId) {
      return NextResponse.json({ ok: true });
    }

    const paymentApi = new Payment(getMercadoPagoClient());
    const payment = await paymentApi.get({ id: paymentId });
    const orderId = payment.external_reference;

    if (!orderId) {
      return NextResponse.json({ ok: true });
    }

    const status = payment.status === "approved" ? "paid" : payment.status || "pending";

    const currentOrder = await prisma.order.findUnique({
      where: { id: orderId },
      include: { items: true }
    });

    if (!currentOrder) {
      return NextResponse.json({ ok: true });
    }

    await prisma.order.update({
      where: { id: orderId },
      data: {
        status,
        mercadoPagoId: String(payment.id),
        mercadoPagoStatus: payment.status || null
      }
    });

    if (status === "paid") {
      for (const item of currentOrder.items) {
        await prisma.product.update({
          where: { id: item.productId },
          data: { stock: { decrement: item.quantity } }
        });
      }
    }

    return NextResponse.json({ ok: true });
  } catch (error) {
    return NextResponse.json({ ok: false, error: String(error) }, { status: 500 });
  }
}

export async function GET() {
  return NextResponse.json({ ok: true });
}
'''
files['app/api/admin/login/route.ts'] = r'''import { NextResponse } from "next/server";
import { createSessionValue, SESSION_COOKIE_NAME } from "@/lib/auth";

export async function POST(request: Request) {
  const formData = await request.formData();
  const email = String(formData.get("email") || "");
  const password = String(formData.get("password") || "");

  if (email !== process.env.ADMIN_EMAIL || password !== process.env.ADMIN_PASSWORD) {
    return new NextResponse(`
      <html><body style="background:#09090b;color:white;font-family:Arial;padding:30px;">
      <h1>Login inválido</h1>
      <p>Volte e tente novamente.</p>
      <a href="/admin/login" style="color:#34d399;">Ir para o login</a>
      </body></html>
    `, { headers: { "content-type": "text/html" }, status: 401 });
  }

  const response = NextResponse.redirect(new URL("/admin", request.url));
  response.cookies.set(SESSION_COOKIE_NAME, createSessionValue(email), {
    httpOnly: true,
    sameSite: "lax",
    secure: process.env.NODE_ENV === "production",
    path: "/",
    maxAge: 60 * 60 * 24 * 7
  });
  return response;
}
'''
files['app/api/admin/logout/route.ts'] = r'''import { NextResponse } from "next/server";
import { SESSION_COOKIE_NAME } from "@/lib/auth";

export async function POST() {
  const response = NextResponse.json({ ok: true });
  response.cookies.set(SESSION_COOKIE_NAME, "", { path: "/", maxAge: 0 });
  return response;
}
'''
files['README.md'] = r'''# BarberPro - Projeto completo de barbearia

Este projeto entrega:

- agendamento online de corte, barba, sobrancelha e outros procedimentos
- geração de mensagem para o WhatsApp do barbeiro
- painel do barbeiro para ver horários e pedidos
- loja de produtos
- checkout com Mercado Pago
- webhook para atualizar pedido pago

## 1) Tecnologias usadas

- Next.js 14
- TypeScript
- Prisma
- SQLite no desenvolvimento
- Mercado Pago Checkout Pro
- Tailwind CSS

## 2) Estrutura principal

- `app/agendar` -> página de agendamento
- `app/produtos` -> loja
- `app/admin` -> painel do barbeiro
- `app/api/appointments` -> cria agendamento
- `app/api/checkout` -> cria preferência do Mercado Pago
- `app/api/mercadopago/webhook` -> recebe retorno do pagamento
- `prisma/schema.prisma` -> banco de dados

## 3) Como rodar localmente

### Instalar dependências

```bash
npm install
```

### Criar o arquivo de ambiente

Copie o `.env.example` para `.env`:

```bash
cp .env.example .env
```

No Windows PowerShell:

```powershell
Copy-Item .env.example .env
```

### Rodar o banco e gerar o Prisma Client

```bash
npx prisma migrate dev --name init
npx prisma generate
npm run seed
```

### Subir o projeto

```bash
npm run dev
```

Abra:

```text
http://localhost:3000
```

## 4) Credenciais iniciais do painel

As credenciais ficam no `.env`:

```env
ADMIN_EMAIL="admin@barbearia.com"
ADMIN_PASSWORD="123456"
```

Acesse:

```text
http://localhost:3000/admin/login
```

## 5) Configurar o WhatsApp do barbeiro

No `.env`, preencha:

```env
BARBER_WHATSAPP_NUMBER="5511999999999"
```

Quando um cliente agenda, o sistema cria um link `wa.me` com a mensagem pronta para o barbeiro.

### Observação importante

Essa versão usa **link para WhatsApp com mensagem pronta**, que é o jeito mais simples de colocar no ar rápido.

Se quiser envio automático sem abrir o WhatsApp, depois você pode trocar para:

- WhatsApp Cloud API
- Twilio WhatsApp
- Z-API / UltraMsg / outro gateway

## 6) Configurar o Mercado Pago

No `.env`, preencha:

```env
MERCADO_PAGO_ACCESS_TOKEN="SEU_TOKEN"
NEXT_PUBLIC_APP_URL="https://seu-dominio.com"
```

No painel do Mercado Pago, configure a URL de webhook para:

```text
https://seu-dominio.com/api/mercadopago/webhook
```

## 7) Como colocar no ar

## Opção recomendada para começo

- Front-end + back-end: Vercel
- Banco em produção: Neon PostgreSQL ou Supabase PostgreSQL

### Passo a passo

#### 1. Suba o projeto para o GitHub

```bash
git init
git add .
git commit -m "Projeto inicial barbearia"
```

Crie um repositório no GitHub e rode:

```bash
git remote add origin https://github.com/SEU-USUARIO/barbearia-app.git
git branch -M main
git push -u origin main
```

#### 2. Criar conta na Vercel

Entre na Vercel e importe o repositório.

#### 3. Configurar variáveis de ambiente

Na Vercel, adicione:

- `DATABASE_URL`
- `ADMIN_EMAIL`
- `ADMIN_PASSWORD`
- `AUTH_SECRET`
- `NEXT_PUBLIC_APP_URL`
- `BARBER_WHATSAPP_NUMBER`
- `MERCADO_PAGO_ACCESS_TOKEN`
- `MERCADO_PAGO_WEBHOOK_SECRET` (opcional nessa versão)

#### 4. Banco em produção

### Se usar Neon/Postgres

Troque o provider do Prisma para PostgreSQL:

No arquivo `prisma/schema.prisma`, altere:

```prisma
datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}
```

para:

```prisma
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
```

Depois rode localmente:

```bash
npx prisma migrate dev --name postgres
```

Depois faça commit dessa mudança e envie para o GitHub.

#### 5. Deploy

A própria Vercel vai buildar o projeto.

Configure o comando de build como padrão:

```text
npm run build
```

#### 6. Rodar migrations em produção

Você pode usar:

```bash
npx prisma migrate deploy
```

ou configurar no pipeline da hospedagem.

## 8) Melhorias que você pode fazer depois

- selecionar barbeiros dinâmicos pelo banco
- agenda com bloqueio de horários
- envio automático por WhatsApp API
- cadastro de múltiplos administradores
- imagens de produtos por upload
- cupom de desconto
- cálculo de frete
- Pix e cartão com checkout transparente
- painel de relatórios

## 9) Limitações desse MVP

- login do painel é simples, com usuário e senha no `.env`
- WhatsApp é via link com mensagem pronta
- sem frete e sem cálculo de entrega
- sem upload de imagens no painel

## 10) Próximo passo ideal

Primeiro coloque essa versão no ar.
Depois evolua para:

- PostgreSQL
- autenticação robusta
- WhatsApp API real
- painel CRUD completo de serviços e produtos
'''
files['LICENSE'] = 'MIT\n'

for path, content in files.items():
    file_path = root / path
    file_path.parent.mkdir(parents=True, exist_ok=True)
    file_path.write_text(content, encoding='utf-8')

print('generated', len(files), 'files')
